### ISSUE TITLE
Plugins and themes can't be installed

### ISSUE THREAD

**Issue by pierlon** [WordPress/wpdev-docker-images#13]
Currently, in order to install plugins or themes (or any file the PHP-FPM process modifies), I have to change the ownership of `src/wp-content` to the PHP-FPM user process.

An easy way to solve this is to dynamically change the UID & GID of the PHP-FPM user upon container startup, as what [devilbox](https://github.com/devilbox/docker-php-fpm#the-solution) does. I can submit a PR with an example of this if needed.

**Comment by pento** [comment]
Thanks for the bug report, @pierlon!

Given that these images are intended to run as dev containers, I don't think it's necessary to worry about trying to match UID/GID. Instead, we can just run everything as root (for example, this is what [the WP-CLI container does](https://github.com/WordPress/wpdev-docker-images/blob/master/Dockerfile-cli.template#L26)).

If you feel like putting together a PR, that'd be awesome! At first glance, it seems like having the entrypoint script alter `user` and `group` in `/usr/local/etc/php-fpm.d/www.conf` would do the trick, but I'm not particularly attached to the method. 🙂

**Comment by pierlon** [comment]
You _could_ run the PHP-FPM process as root, but that brings problems of its own. With that approach, I'd have to `chown` the files to my user to modify them. Setting the UID/GID to the current user would solve that.

I'm also working on [saving mails sent by Wordpress to disk](https://wordpress.slack.com/archives/C02RQBWTW/p1567283941425600?thread_ts=1567136397.337000&cid=C02RQBWTW), and they can't be saved without manually `chown`ing the directory to the UID/GID of the PHP-FPM process.

My PR does include altering the UID and GID of the PHP-FPM process, which I'll get into detail with when I submit it :rocket:.
