### ISSUE TITLE
Update PHP images

### ISSUE THREAD

**Issue by ocean90** [WordPress/wpdev-docker-images#21]
The version of the current PHP 7.4 image is 7.4.0RC6 while the latest version is PHP 7.4.3.

It looks like the images are build on Travis but the [last build](https://travis-ci.com/WordPress/wordpress-develop-security) was about a month ago. Should we create a cronjob on Travis to let a build run once a week?
<img width="948" alt="travis-cron" src="https://user-images.githubusercontent.com/617637/75524006-5f68cd80-5a0d-11ea-8567-f3d90b8e40ba.png">

@pento Is this something you can set up?

**Comment by pento** [comment]
Good idea, thanks @ocean90.

I've configured a weekly build to run against `master`.
