### ISSUE TITLE
Docker Hub: Apply for OSS plan

### ISSUE THREAD

**Issue by pento** [WordPress/wpdev-docker-images#35]
Docker is [introducing subscription plans](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/), which include rate limits on pulls.

They're planning on adding an OSS plan, which can be applied for [here](https://docs.google.com/forms/d/e/1FAIpQLSd11DjfgeaKSRdqp6Br85MzQQuM4igt-xmn6rmzA2StFGLndQ/viewform).

While we're looking at it, I'm currently the only person listed on the `wordpressdevelop` org. I'm happy to add others (I'll just need your Docker ID), and someone active on WordPress can run through the OSS plan application.

**Comment by pento** [comment]
@dd32: Can you handle this, or suggest someone who can?

**Comment by dd32** [comment]
The OSS plan seems like a reasonable thing to apply for. Feel free to add me to DockerHub (`dionhulse`) and I'll either handle it or get someone else to.

It's worth noting, that the plan will only apply to WordPress.org pulls (ie. Travis and/or GitHub actions) and not anyone else who uses those images (ie. locally via wp-env or similar).

I assume that our Travis/GitHub actions runs would easily pass the 100/200 per 6hr non-plan limits especially with PR runs included.
Are there any stats right now of how many pulls we actually issue?
(I'm thinking there's at least 1 pull from dockerhub per travis/github task, with maybe an average of 10 pulls per PR/Commit run?)

**Comment by pento** [comment]
Cool, I've added you as an owner to the repo.

There are no hourly stats that I could find. There's only the [public figures](https://hub.docker.com/u/wordpressdevelop) showing total pulls for each image. For a conservative estimate of 300k pulls over the last year, that averages out to ~200 pulls/6 hours. I'm assuming that the actual figure is higher than that, since we're using GitHub more.

**Comment by desrosj** [comment]
This came up again over the last few weeks with the email announcement that Docker was sun-setting Free Teams organizations.

After community at large overwhelming expressed disapproval with this change (even after an [in depth updated FAQ post to try and better communicate the change](https://web.archive.org/web/20230322142318/https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)), [Docker has decided not to sunset Free Team organizations](https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/).

In response to the original announcement, @dd32 applied for the open source program and we were approved. It takes several weeks for them to update our team, so I'll leave this open until then.

![Screenshot 2023-03-29 at 11 42 55](https://user-images.githubusercontent.com/359867/228593469-0f8f8522-ecd8-4d84-992c-70baa3bbbe32.png)

My reading of this chart from their pricing page is that personal Docker accounts are limited to 200 pulls per 6 hours, and images pushed by those users are limited to 100 pulls per 6 hours for anonymous users. Pro and higher have N/A listed for anonymous users, which could be interpreted as there being no limit to the number of pulls an anonymous user can pull unlimited images (probably has some underlying rate limit) or the same.

The [Download rate limit page in the Docker Hub documentation](https://docs.docker.com/docker-hub/download-rate-limit/#whats-the-download-rate-limit-on-docker-hub) says "For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address" but doesn't say anything to clarify the N/A shown in the pricing table.

I wish that all this was more clearly communicated, but the OSS program could have more lenient rate limiting.

**Comment by desrosj** [comment]
The name of this changed (it's now Docker-Sponsored Open Source), but `wordpressdevelop` has been on that since March of 2023 when they approved the application that @dd32 sent.

Closing this out.
