### ISSUE TITLE
Having composer pre-installed in the php images?

### ISSUE THREAD

**Issue by Nikschavan** [WordPress/wpdev-docker-images#6]
I think if these images can be used in the `wp scaffold` command for [gitlab-ci configuration](https://github.com/wp-cli/scaffold-command/blob/master/templates/plugin-gitlab.mustache#L28) to replace current [tetraweb/php](https://hub.docker.com/r/tetraweb/php/tags) images which do not seem to be actively maintained.

If the composer cannot be installed from `wpdev-docker-images` images itself, there is an alternative to install it in the CI itself in the `before_Script` section, but it will be a bit faster to complete CI builds if it is preinstalled.

**Comment by pento** [comment]
As these Docker images are built with Core in mind, I'm inclined to think that they wouldn't be a good option for the `wp scaffold` CI templates. 

[Devilbox](https://github.com/devilbox/docker-php-fpm) is probably a better option for a maintained, more generic PHP image.
