### ISSUE TITLE
Missing Xdebug from phpunit and other images

### ISSUE THREAD

**Issue by kasparsd** [WordPress/wpdev-docker-images#89]
It is currently impossible to generate code coverage reports using the `phpunit` or any other images containing PHP that are generated by this repository.

`@wordpress/env` attempts to enable Xdebug support here:

https://github.com/WordPress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/env/lib/init-config.js#L84-L90

but it doesn't do it for images that could actually be used for running CLI tasks such as `phpunit`, `tests`, `cli` and others as reported here https://github.com/WordPress/gutenberg/issues/42286

**Comment by kasparsd** [comment]
Could we update all images to install Xdebug but leave it disabled by default? Or install and enable Xdebug only for `php-cli` usage so that it doesn't impact the performance of non-CLI requests?

**Comment by desrosj** [comment]
Hey @kasparsd,

xDebug is currently installed and disabled by default. WordPress Core actually [generates a code coverage report using them and submits it to Codecov.io](https://github.com/WordPress/wordpress-develop/actions/runs/3457546108/jobs/5771070289#step:4:61). 

To boot the Docker containers with xDebug, a few environment variables need be set:
- `LOCAL_PHP_XDEBUG` needs to be set to `true`.
- To configure xDebug to generate coverage reports, `LOCAL_PHP_XDEBUG_MODE` needs to be set to `coverage` (`develop,debug` is the default).

Could you give this a try, or confirm that you've tried this and are experiencing issues?

**Comment by kasparsd** [comment]
Thanks! I'm not sure how I missed the `LOCAL_PHP_XDEBUG` conditional in `common.sh`:

https://github.com/WordPress/wpdev-docker-images/blob/2106858ec7c65fa4975f1880fd9d5d902837f1be/entrypoint/common.sh#L4-L11

So we just need to update `wp-env` to set these environment variables whenever `xdebug` is being requested via the custom CLI param https://github.com/WordPress/gutenberg/issues/42286
